name: Generate Snake Animation

on:
  schedule:
    # Executa a cada 24 horas para atualizar a cobrinha
    - cron: "0 0 * * *" 
  workflow_dispatch: # Permite rodar o script manualmente
  push:
    branches:
    - main # Atualiza sempre que vocÃª fizer um push no README

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: 2007murilocortez
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
